[package]
name = "comparing_hashsets"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
hashbrown = "0.14.5"
rustc-hash = "2.0.0"

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
name = "hashsets"
harness = false
